### ISSUE TITLE
Solutions 3000

### ISSUE THREAD

**Issue by manningoz** [EHylands/homebridge-boschcontrolpanel_bgseries#16]
With the settings enable as outlined on the solutions panel, it fails to connect. 

openssl s_client -connect 192.168.1.134:7700

is there a something that needs to be disabled/enabled for this to work and can RSC work simultaneously or is this potentially the reason it’s not working?

**Comment by manningoz** [comment]
Pls note that “Select Encryption and Security Settings—> Web and Automation Security” is already enabled and was enabled from factory.

**Comment by EHylands** [comment]
Automation protocol on Solution panel will only allow for one simultaneous connection on port 7700.

Can you connect while not running RSC ?

**Comment by manningoz** [comment]
Do I need to disable it on the solutions via the keypad or just not be using it at the time I am trying to connect?

**Comment by manningoz** [comment]
Thanks again - I disabled cloud on the panel and it now works

**Comment by EHylands** [comment]
Thank you for reporting this.

I still don't own a Solution Panel and have not yet been able to fully document the panel configuration process.

Will note in readme file that plugin won't be able to connect if RSC app is connected through cloud connection.
