### ISSUE TITLE
AMAX support

### ISSUE THREAD

**Issue by sanjay900** [EHylands/homebridge-boschcontrolpanel_bgseries#17]
Hey mate, not sure if you saw the progress on the home assistant integration, but I did get my hands on a AMAX 2100, and have figured out what the auth process entails for them.

https://github.com/mag1024/bosch-alarm-mode2/pull/25

They require using both an automation passcode AND an installer code.
Interestingly, the solution panels also work with this strategy, and I will be migrating the home assistant integration to use this method too, as some commands I wanted for subscription support are installer only.

If you intend to support outputs for the solution panels, it may be worth making the same change yourself too, as mapping the outputs for solution panels to their subscription counterparts does require reading the configuration from the panel, which requires being authenticated as an installer.

**Comment by EHylands** [comment]
Hi @sanjay900 ,
Thank you for reaching out !
I subscribed to your project notifications and have been closely following all your recents commits 😀.

Output management with subscriptions on Solution panels looks quite tricky. Will definitely look into this !
