### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by jmhadaller** [EHylands/homebridge-boschcontrolpanel_bgseries#18]
Where are the installation instructions? You outline what the plugin can do, but don't give any indication on how it's installed...

**Comment by EHylands** [comment]
Hi,
which Bosch panel are you using ?
Are you familiar with Homebridge ?

**Comment by jmhadaller** [comment]
I have zero experience with homebridge, I am switching from a old honeywell panel with totalconnect to a B5512.

**Comment by EHylands** [comment]
First, you need to install Homebridge server on a computer that will always be powered on on your local network
[https://github.com/homebridge/homebridge/wiki](https://github.com/homebridge/homebridge/wiki)

After, you need to install Homebridge UI plugin for web configuration interface to be enabled.
[https://github.com/homebridge/homebridge-config-ui-x#readme](https://github.com/homebridge/homebridge-config-ui-x#readme)

Finally, you will be able to install this plugin through Homebridge UI interface.

I can further assist once you have Homebridge server up and running.

**Comment by jmhadaller** [comment]
I already have it installed... I just can't figure out how to install the plugin.






---- On Wed, 20 Dec 2023 18:21:59 -0600 Eric Hylands ***@***.***> wrote ---





First, you need to install Homebridge server on a computer that will always be powered on on your local network
 https://github.com/homebridge/homebridge/wiki
After, you need to install Homebridge UI plugin for web configuration interface to be enabled.
 https://github.com/homebridge/homebridge-config-ui-x#readme
Finally, you will be able to install this plugin through Homebridge UI interface.

I can further assist once you have Homebridge server up and running.

**Comment by EHylands** [comment]
You can use Homebridge UI web interface and search for the plugin:
<img width="425" alt="Screenshot 2023-12-20 at 19 28 00" src="https://github.com/EHylands/homebridge-boschcontrolpanel_bgseries/assets/90003064/e8e29a1c-5f89-4057-8dc3-1af3f3713560">

You can also install the plugin through command line:
`npm install homebridge-boschcontrolpanel_bgseries`

**Comment by EHylands** [comment]
you need to search for the following plugin: homebridge-boschcontrolpanel_bgseries

**Comment by jmhadaller** [comment]
I think I got it installed properly, but I've got this error.. Not sure what this means.
![image](https://github.com/EHylands/homebridge-boschcontrolpanel_bgseries/assets/154466150/e43ab5fa-3aba-4831-9d5e-fdc352b1860a)

**Comment by EHylands** [comment]
Which firmware is you B5512 running ?
Older Bosch firmware would only support TLS 1.0 and not supported by node for secure connection to panel.

You can check you panel TLS version by running the following command:
`openssl s_client -connect PanelP:7700`

**Comment by jmhadaller** [comment]
3.03.014
![image](https://github.com/EHylands/homebridge-boschcontrolpanel_bgseries/assets/154466150/efd35093-de08-4c0d-ad59-96e1f2aa3fd7)

**Comment by EHylands** [comment]
I don't think the automation interface is running on your panel. 
Did you set Automation Device to Mode 2  with RPS on your panel ?
https://github.com/EHylands/homebridge-boschcontrolpanel_bgseries/blob/master/README_US.md

**Comment by jmhadaller** [comment]
Yes I am. 
![image](https://github.com/EHylands/homebridge-boschcontrolpanel_bgseries/assets/154466150/34a1d320-a091-417b-8e69-fbcd7ec9ba7b)

**Comment by EHylands** [comment]
Just saw your previous message with firmware 3.03.014
It probably doesn't support newer TLS version
I would upgrade to newest 3.14 firmware.
https://commerce.boschsecurity.com/us/en/B5512-Control-Panels/p/6085453963/

**Comment by jmhadaller** [comment]
It started working after updating the firmware. Thank you for your help!!
