### ISSUE TITLE
Installation method

### ISSUE THREAD

**Issue by fredhandle** [EHylands/homebridge-boschcontrolpanel_bgseries#2]
Hi. I'm totally familiar with the Bosch B Series controllers. However relatively new to Home Assistant.
What is the method to install your homebridge-boschscontrolpanel plugin. Could you point me in the right direction please.

ThanksColin

**Comment by sanjay900** [comment]
If your after home assistant integration and have a solution 3000, ive written something specifically for that
https://github.com/sanjay900/solution3000-home-assistant

**Comment by fredhandle** [comment]
Thanks sanjay900 but I have a B8512G controller

**Comment by EHylands** [comment]
@fredhandle This plugin is for Homebridge. 
I did not look into HomeAssitant.

**Comment by fredhandle** [comment]
@EHylands sorry I didn’t make that leap not being familiar with Homebridge. Is there any chance of developing a Home Assistant version?

**Comment by EHylands** [comment]
@fredhandle Unfortunately, all my house integration systems are well supported by Homebridge for the moment and I have no plan to switch to HomeAssistant. 

With proper documentation, I think it would be fairly easy to write an HomeAssistant plugin for anyone up to the challenge!
