### ISSUE TITLE
Bosch Solution 3000 - Alarm detection error

### ISSUE THREAD

**Issue by djwaz** [EHylands/homebridge-boschcontrolpanel_bgseries#26]
Hi Eric

I have started getting a message in the log of Homebridge saying:

TypeError: Cannot read properties of undefined (reading '0')
    at BGProtocolHandler01.Mode2WhatAreYou_CF03 (/homebridge/node_modules/homebridge-boschcontrolpanel_bgseries/src/BGProtocolHandler01.ts:150:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BGController.Configure (/homebridge/node_modules/homebridge-boschcontrolpanel_bgseries/src/BGController.ts:232:13)
[6/22/2024, 9:48:07 PM] Got SIGTERM, shutting down Homebridge...

Any suggestions?

**Comment by EHylands** [comment]
Hi, 
Any recent changes ? Did you upgraded to new Solution 3000 firmware ?

My best guest is that you rebooted Homebridge and previous Mode2 connexion to panel has not time out yet and new connextion cannot be established. (Some panel will only allow one Mode connexion at any time).

Try closing Homebridge for 5 min and restart plugin afterward.

**Comment by djwaz** [comment]
Hey Eric

I think that was actually the issue. All working again now. Thank you for creating and sharing this plugin. It is so much easier than Bosch's RSC+ app!

**Comment by EHylands** [comment]
Hi,
Did you updated your panel firmware to new version 2.1.3 ?

Previous firmware would only allow for 1 mode2 automation connection. Homebridge plugin and RSC app could not bet used simultaneously.

2.1.3 panel also enables pushed notifications which the whole experience more pleasant!

**Comment by manningoz** [comment]
Not sure if this deserves a new thread but triggering the alarm on “Home” mode resulting in nothing but errors. the alarm did physically sound but didn’t trigger anything on homebridge. The error in question when it tripped is

[25/06/2024, 06:46:40] [homebridge-boschcontrolpanel_bgseries] Bosch Panel Error (Mode2ReqAlarmAreasByPriority_CF01 NonSpecificError)

firmware 2.1.3 using subscriptions 

[25/06/2024, 06:46:20] [homebridge-boschcontrolpanel_bgseries] Panel: Area1(AREA1): PartOnEntryDelay
[25/06/2024, 06:46:21] [homebridge-boschcontrolpanel_bgseries] Panel: Point1(Front Door): Open
[25/06/2024, 06:46:32] [homebridge-boschcontrolpanel_bgseries] Panel: Point1(Front Door): Normal
[25/06/2024, 06:46:40] [homebridge-boschcontrolpanel_bgseries] Bosch Panel Error (Mode2ReqAlarmAreasByPriority_CF01 NonSpecificError)
[25/06/2024, 06:46:47] [homebridge-boschcontrolpanel_bgseries] Panel: Area1(AREA1): PartOnEntryDelay

**Comment by EHylands** [comment]
My bad
Command 0x22 - ReqAlarmAreasByPriority_CF01: false
Will have to use another command (0x23) to retrieve alarm detail on Solution 3000 panels.
Will issue a fix

**Comment by EHylands** [comment]
It should work in version 0.8.2-beta.0
I gave it a try with all available arming modes.
Please let me know !

**Comment by manningoz** [comment]
Still some issues - errors when disarming now
![IMG_2510](https://github.com/EHylands/homebridge-boschcontrolpanel_bgseries/assets/125713047/131fe6ac-b087-49bf-8345-5991e92d6774)

**Comment by EHylands** [comment]
@manningoz  0.8.2-beta.1

I made sure I did't backported the error that was causing the Mode2ReqOutputStatus Protocol error in previous version.
Looks like a different error ...
Added some debug code to Mode2ReqOutputStatus

**Comment by manningoz** [comment]
> @manningoz 0.8.2-beta.1
> 
> I made sure I did't backported the error that was causing the Mode2ReqOutputStatus Protocol error in previous version. Looks like a different error ... Added some debug code to Mode2ReqOutputStatus

Thank you. Have done multiple tests. The homebridge now reacts correctly for home mode.

However there are still errors displayed as below. Does not seem to affect operation though - perhaps it is trying to engage outputs which are not supported on solutions panel?

![IMG_2658](https://github.com/EHylands/homebridge-boschcontrolpanel_bgseries/assets/125713047/d2f8b3f0-7976-4920-a3d6-89bcb6bf6c45)

**Comment by EHylands** [comment]
Strange
Mode2ReqOutputStatus
Panel is sending 01 02 fc 00
This is not a valid answer for Mode2ReqOutputStatus.
We normally expect a fe packet rather a fc with that function.

A packet is read out of order at some point.

I suspect StartSubscription command at plugin start time ! 

Will investigate!

**Comment by manningoz** [comment]
Now this error appears and I cannot connect

![IMG_2796](https://github.com/EHylands/homebridge-boschcontrolpanel_bgseries/assets/125713047/228c119d-6a2f-4843-af19-d37392ccba60)

**Comment by EHylands** [comment]
This happen when to many connections are established with the oanel. Need to let it 'cool down' a bit before restarting homebridge soo the panel properly times out the active connections.

Its on my to do list to gracefully waitbabd reconnect with user rebooting

**Comment by manningoz** [comment]
> This happen when to many connections are established with the oanel. Need to let it 'cool down' a bit before restarting homebridge soo the panel properly times out the active connections.
> 
> Its on my to do list to gracefully waitbabd reconnect with user rebooting

Strange behaviour is occurring in the beta so I have reverted to the stable release. If the alarm is armed through the plugin it does work the first time after the plugin has initialised. However every subsequent arming action is non responsive ie there is no log and no response, however the motion behaviour does appear as normal.

Also worth noting is that an arming action/disarming action that is requested when the alarm is in the same state as what has been requested from HomeKit causes a Mode2armpanelareas Noauthority error

**Comment by EHylands** [comment]
Hi @manningoz 

I just published homebridge-boschcontrolpanel_bgseries@0.8.2-beta.3

Went through you log error pictures and code.
Mode2ReqOutputStatus and Mode2ArmPanelAreas response packets were received and read out of order.
Think I had some concurrency error that I fixed by adding semaphore to Mode2ReqOutputState command. 

Do your Ouput #1 and #4 change anytime your panel is armed and disarmed ?

Output status can't be esasily read from Protocol 0x02 on Solutions panels. We have to resort to calling Protocol 0x01 Mode2ReqOutputStatus anytime an Output pushed notification is received through Protocol 0x02 ...

If you encounter another error, please send full log file so I can trace packet order back.

**Comment by manningoz** [comment]
> Hi @manningoz
> 
> I just published homebridge-boschcontrolpanel_bgseries@0.8.2-beta.3
> 
> Went through you log error pictures and code. Mode2ReqOutputStatus and Mode2ArmPanelAreas response packets were received and read out of order. Think I had some concurrency error that I fixed by adding semaphore to Mode2ReqOutputState command.
> 
> Do your Ouput #1 and #4 change anytime your panel is armed and disarmed ?
> 
> Output status can't be esasily read from Protocol 0x02 on Solutions panels. We have to resort to calling Protocol 0x01 Mode2ReqOutputStatus anytime an Output pushed notification is received through Protocol 0x02 ...
> 
> If you encounter another error, please send full log file so I can trace packet order back.

@EHylands appears to be working well. Thank you
