### ISSUE TITLE
Mode2.WhatAreYou error

### ISSUE THREAD

**Issue by djwaz** [EHylands/homebridge-boschcontrolpanel_bgseries#32]
Hey Eric, my homebridge login has suddenly flagged this error message up. Nothing has been changed in the plugin or the homebridge itself and it has just stopped working.
Homebridge version 1.8.5 and node-js version 20.11.0 (so that my eufy doorbell camera works).

any suggestions?

I have reset the network connection, restarted the homebridge VM and homebridge itself and checked the plugin settings.

![IMG_1890](https://github.com/user-attachments/assets/2e853239-0076-4b35-b0f9-4bf943058620)

**Comment by EHylands** [comment]
Are you using a Solution panel ?

Solution panels can only accept 1 active connection at a time.

Wait a few minutes before restarting Homebridge and the previous active connection to the panel should have timed out.
